### ISSUE TITLE
False negative and false positive in sshd_idle_timeout

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#179]
CIS benchmark recommendss "ClientAliveInterval is 300 or less and ClientAliveCountMax is 3 or less."  But the implementation uses string match.  This can cause false negatives and false positives.

For example, centos-7-level-1-scored-v2-1-0.yaml
```
   sshd_idle_timeout:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: ClientAliveInterval 300
            pattern: ^ClientAliveInterval
            tag: CIS-5.2.13
        - /etc/ssh/sshd_config:
            match_output: ClientAliveCountMax 0
            pattern: ^ClientAliveCountMax
            tag: CIS-5.2.13
      description: Ensure SSH Idle Timeout Interval is configured
```
