### ISSUE TITLE
False Flags on User Home Directories

### ISSUE THREAD

**Issue by wschmrdrNS** [hubblestack/hubble#280]
In the misc.py module, the functions "check_all_users_home_directory", "check_users_home_directory_permissions", and "check_users_own_their_home" have inconsistent script checks with what is available in "CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.1.0.pdf", in that they do not skip the users that have a shell of "/bin/false" or "/user/sbin/nologin". This is causing the user "nobody" to be flagged as failing because it has a UID of 65534, but should not apply because it is non-login. The max_system_uid should not be increased to account for this, because it would then skip users that should have home directories and be validated as such.

Here is a snippet of the custom Nova profile I am using to conform with the spec update for Ubuntu 16.04 that calls these functions:

```
misc:
  check_home_directory:
    data:
      Ubuntu-16.04:
        tag: CIS-6.2.7
        function: check_all_users_home_directory
        kwargs:
            max_system_uid: 999
    description: Ensure all users' home directories exist
  home_directory_permission:
    data:
      Ubuntu-16.04:
        tag: CIS-6.2.8
        function: check_users_home_directory_permissions
    description: 'Ensure users home directories permissions are 750 or more restrictive'
  check_owner_home:
    data:
      Ubuntu-16.04:
        tag: CIS-6.2.9
        function: check_users_own_their_home
        kwargs:
            max_system_uid: 999
    description: Ensure users own their home directories

```
