### ISSUE TITLE
Pulsar not recursively adding directory watches at startup

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#327]
It appears that pulsar is not recursively adding directory watches at startup.

For example, with this config:

```
/root:
  exclude:
    - \/root\/sudoers\.d\/.*\.swp$:
        regex: True
  recurse: True
  auto_add: True
checksum: sha256
stats: True
batch: True
```

If I add the directory `/root/sudoers.d/` *after* starting hubble, it will see its addition, add a new watch, and then any files inside of that new directory correctly trigger events.

However, if that directory is present when hubble is started, no files created or modified in that directory will trigger.
