### ISSUE TITLE
Inconsistent indentation for description label across multiple Hubble audit files

### ISSUE THREAD

**Issue by alias454** [hubblestack/hubble#540]
Hi again. I was starting to add missing audits and ran into another anomaly, this time with indentation for the misc functions section. It appears the indentation for the description is nested differently than in the example from https://github.com/hubblestack/hubble/blob/develop/hubblestack/files/hubblestack_nova/misc.py.

Some of the checks are nested like so:
```
  system_account_non_login:
    data:
      '*':
       tag: CIS-5.4.2
       function: system_account_non_login
       description: Ensure system accounts are non-login
```

But then in other files they are nested like the example in the misc.py file:
```
  default_group_for_root_account:
    data:
      Ubuntu-16.04:
        tag: CIS-5.4.3
        function: default_group_for_root
    description: 'Ensure default group for the root account is GID 0'
```

Should these all be nested the same or is there some voodoo under the hood that makes this mostly irrelevant functionally?

Regards,
Brandon
